# Generated by Django 5.0.3 on 2024-03-19 02:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='kafedra',
            name='slug',
            field=models.SlugField(blank=True, unique=True),
        ),
        migrations.AddField(
            model_name='napravlenie',
            name='slug',
            field=models.SlugField(blank=True, unique=True),
        ),
        migrations.AddField(
            model_name='photogallery',
            name='slug',
            field=models.SlugField(blank=True, unique=True),
        ),
        migrations.AddField(
            model_name='photogallery',
            name='title',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='Название'),
        ),
        migrations.AddField(
            model_name='videogallery',
            name='slug',
            field=models.SlugField(blank=True, unique=True),
        ),
        migrations.AlterField(
            model_name='napravlenie',
            name='kafedra',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='napravleniya', to='home.kafedra', verbose_name='Кафедра'),
        ),
        migrations.AlterField(
            model_name='napravlenie',
            name='title',
            field=models.CharField(max_length=150, verbose_name='Направление'),
        ),
    ]
