# Generated by Django 5.0.3 on 2024-03-19 02:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_kafedra_slug_napravlenie_slug_photogallery_slug_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Napravlenie',
        ),
    ]
