# Generated by Django 5.0.3 on 2024-03-19 05:04

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_delete_napravlenie'),
    ]

    operations = [
        migrations.CreateModel(
            name='KafedraDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(db_index=True, max_length=150, verbose_name='Название кафедры')),
                ('slug', models.SlugField(blank=True, unique=True)),
                ('text', ckeditor.fields.RichTextField()),
            ],
            options={
                'verbose_name': 'Детальный просмотр кафедры',
                'verbose_name_plural': 'Детальный просмотр кафедры',
            },
        ),
    ]
