# Generated by Django 5.0.3 on 2024-03-19 05:10

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_kafedradetail'),
    ]

    operations = [
        migrations.DeleteModel(
            name='KafedraDetail',
        ),
        migrations.AddField(
            model_name='kafedra',
            name='text',
            field=ckeditor.fields.RichTextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='kafedra',
            name='title',
            field=models.CharField(max_length=150, null=True, verbose_name='Название кафедры'),
        ),
    ]
