# Generated by Django 5.0.3 on 2024-03-19 09:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0007_delete_direction'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='kafedra',
            name='text',
        ),
    ]
