# Generated by Django 5.0.3 on 2024-03-19 09:25

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0008_remove_kafedra_text'),
    ]

    operations = [
        migrations.AddField(
            model_name='kafedra',
            name='text',
            field=ckeditor.fields.RichTextField(blank=True, null=True),
        ),
    ]
