# Generated by Django 5.0.3 on 2024-03-20 06:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0012_remove_aboutus_text_remove_aboutus_title_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='aboutus',
            old_name='about_us',
            new_name='text',
        ),
    ]
