# Generated by Django 5.0.3 on 2024-03-20 06:49

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0013_rename_about_us_aboutus_text'),
    ]

    operations = [
        migrations.AddField(
            model_name='aboutus',
            name='title',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='О нас'),
        ),
        migrations.AlterField(
            model_name='aboutus',
            name='text',
            field=ckeditor.fields.RichTextField(blank=True, null=True),
        ),
    ]
