# Generated by Django 5.0.3 on 2024-03-23 03:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0014_aboutus_title_alter_aboutus_text'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='slide',
            name='title',
        ),
    ]
