# Generated by Django 5.0.3 on 2024-03-23 04:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0017_alter_news_text'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ads',
            old_name='image',
            new_name='ads_image',
        ),
        migrations.RenameField(
            model_name='director',
            old_name='image',
            new_name='director_image',
        ),
        migrations.RenameField(
            model_name='events',
            old_name='image',
            new_name='events_image',
        ),
        migrations.RenameField(
            model_name='news',
            old_name='image',
            new_name='news_image',
        ),
    ]
