# Generated by Django 5.0.3 on 2024-03-23 05:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0018_rename_image_ads_ads_image_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='events',
            name='events_image',
            field=models.ImageField(blank=True, null=True, upload_to='events_image/', verbose_name='фотки для события'),
        ),
    ]
