# Generated by Django 5.0.3 on 2024-03-23 05:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0021_rename_ads_image_ads_ad_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ads',
            old_name='ad_image',
            new_name='ads_image',
        ),
    ]
