# Generated by Django 5.0.3 on 2024-03-23 07:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0022_rename_ad_image_ads_ads_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='videogallery',
            name='title',
            field=models.CharField(blank=True, max_length=150, verbose_name='Название'),
        ),
        migrations.AlterField(
            model_name='videogallery',
            name='video_file',
            field=models.FileField(blank=True, upload_to='videos/', verbose_name='Видеофайл'),
        ),
    ]
