# Generated by Django 5.0.3 on 2024-03-24 06:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0023_alter_videogallery_title_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Ads',
            new_name='Ad',
        ),
    ]
